// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: unixfs.proto

package unixfs_pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Data_DataType int32

const (
	Data_Raw       Data_DataType = 0
	Data_Directory Data_DataType = 1
	Data_File      Data_DataType = 2
	Data_Metadata  Data_DataType = 3
	Data_Symlink   Data_DataType = 4
	Data_HAMTShard Data_DataType = 5
	Data_TokenMeta Data_DataType = 6
)

var Data_DataType_name = map[int32]string{
	0: "Raw",
	1: "Directory",
	2: "File",
	3: "Metadata",
	4: "Symlink",
	5: "HAMTShard",
	6: "TokenMeta",
}

var Data_DataType_value = map[string]int32{
	"Raw":       0,
	"Directory": 1,
	"File":      2,
	"Metadata":  3,
	"Symlink":   4,
	"HAMTShard": 5,
	"TokenMeta": 6,
}

func (x Data_DataType) Enum() *Data_DataType {
	p := new(Data_DataType)
	*p = x
	return p
}

func (x Data_DataType) String() string {
	return proto.EnumName(Data_DataType_name, int32(x))
}

func (x *Data_DataType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Data_DataType_value, data, "Data_DataType")
	if err != nil {
		return err
	}
	*x = Data_DataType(value)
	return nil
}

func (Data_DataType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e2fd76cc44dfc7c3, []int{0, 0}
}

type Data struct {
	Type                 *Data_DataType `protobuf:"varint,1,req,name=Type,enum=unixfs.pb.Data_DataType" json:"Type,omitempty"`
	Data                 []byte         `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
	Filesize             *uint64        `protobuf:"varint,3,opt,name=filesize" json:"filesize,omitempty"`
	Blocksizes           []uint64       `protobuf:"varint,4,rep,name=blocksizes" json:"blocksizes,omitempty"`
	HashType             *uint64        `protobuf:"varint,5,opt,name=hashType" json:"hashType,omitempty"`
	Fanout               *uint64        `protobuf:"varint,6,opt,name=fanout" json:"fanout,omitempty"`
	Mode                 *uint32        `protobuf:"varint,7,opt,name=mode" json:"mode,omitempty"`
	Mtime                *int64         `protobuf:"varint,8,opt,name=mtime" json:"mtime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2fd76cc44dfc7c3, []int{0}
}
func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetType() Data_DataType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Data_Raw
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Data) GetFilesize() uint64 {
	if m != nil && m.Filesize != nil {
		return *m.Filesize
	}
	return 0
}

func (m *Data) GetBlocksizes() []uint64 {
	if m != nil {
		return m.Blocksizes
	}
	return nil
}

func (m *Data) GetHashType() uint64 {
	if m != nil && m.HashType != nil {
		return *m.HashType
	}
	return 0
}

func (m *Data) GetFanout() uint64 {
	if m != nil && m.Fanout != nil {
		return *m.Fanout
	}
	return 0
}

func (m *Data) GetMode() uint32 {
	if m != nil && m.Mode != nil {
		return *m.Mode
	}
	return 0
}

func (m *Data) GetMtime() int64 {
	if m != nil && m.Mtime != nil {
		return *m.Mtime
	}
	return 0
}

type Metadata struct {
	MimeType             *string  `protobuf:"bytes,1,opt,name=MimeType" json:"MimeType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Metadata) Reset()         { *m = Metadata{} }
func (m *Metadata) String() string { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()    {}
func (*Metadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_e2fd76cc44dfc7c3, []int{1}
}
func (m *Metadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metadata.Unmarshal(m, b)
}
func (m *Metadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metadata.Marshal(b, m, deterministic)
}
func (m *Metadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metadata.Merge(m, src)
}
func (m *Metadata) XXX_Size() int {
	return xxx_messageInfo_Metadata.Size(m)
}
func (m *Metadata) XXX_DiscardUnknown() {
	xxx_messageInfo_Metadata.DiscardUnknown(m)
}

var xxx_messageInfo_Metadata proto.InternalMessageInfo

func (m *Metadata) GetMimeType() string {
	if m != nil && m.MimeType != nil {
		return *m.MimeType
	}
	return ""
}

func init() {
	proto.RegisterEnum("unixfs.pb.Data_DataType", Data_DataType_name, Data_DataType_value)
	proto.RegisterType((*Data)(nil), "unixfs.pb.Data")
	proto.RegisterType((*Metadata)(nil), "unixfs.pb.Metadata")
}

func init() { proto.RegisterFile("unixfs.proto", fileDescriptor_e2fd76cc44dfc7c3) }

var fileDescriptor_e2fd76cc44dfc7c3 = []byte{
	// 285 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0xc6, 0x4d, 0x9b, 0x6d, 0xdd, 0xeb, 0x26, 0xe1, 0x45, 0x24, 0x78, 0x90, 0xb0, 0x83, 0xe4,
	0x20, 0x3b, 0xf8, 0x0d, 0x84, 0x21, 0x5e, 0x76, 0xc9, 0xf6, 0x05, 0xb2, 0x2d, 0xa5, 0xa1, 0x7f,
	0x32, 0xda, 0x0c, 0xad, 0xdf, 0xd0, 0x6f, 0x25, 0x69, 0xd7, 0xea, 0x25, 0xe4, 0x97, 0xf7, 0xf9,
	0x85, 0x27, 0x81, 0xc5, 0xa5, 0xb2, 0x5f, 0x69, 0xb3, 0x3e, 0xd7, 0xce, 0x3b, 0x9c, 0x0f, 0x74,
	0x58, 0xfd, 0x44, 0x40, 0x37, 0xda, 0x6b, 0x7c, 0x01, 0xba, 0x6f, 0xcf, 0x86, 0x13, 0x11, 0xc9,
	0xbb, 0x57, 0xbe, 0x1e, 0x23, 0xeb, 0x30, 0xee, 0x96, 0x30, 0x57, 0x5d, 0x0a, 0xb1, 0xb7, 0x78,
	0x24, 0x88, 0x5c, 0xa8, 0xfe, 0x86, 0x47, 0x48, 0x52, 0x5b, 0x98, 0xc6, 0x7e, 0x1b, 0x1e, 0x0b,
	0x22, 0xa9, 0x1a, 0x19, 0x9f, 0x00, 0x0e, 0x85, 0x3b, 0xe6, 0x01, 0x1a, 0x4e, 0x45, 0x2c, 0xa9,
	0xfa, 0x77, 0x12, 0xdc, 0x4c, 0x37, 0x59, 0xd7, 0x60, 0xd2, 0xbb, 0x03, 0xe3, 0x03, 0x4c, 0x53,
	0x5d, 0xb9, 0x8b, 0xe7, 0xd3, 0x6e, 0x72, 0xa5, 0xd0, 0xa1, 0x74, 0x27, 0xc3, 0x67, 0x82, 0xc8,
	0xa5, 0xea, 0xf6, 0x78, 0x0f, 0x93, 0xd2, 0xdb, 0xd2, 0xf0, 0x44, 0x10, 0x19, 0xab, 0x1e, 0x56,
	0x06, 0x92, 0xa1, 0x3f, 0xce, 0x20, 0x56, 0xfa, 0x93, 0xdd, 0xe0, 0x12, 0xe6, 0x1b, 0x5b, 0x9b,
	0xa3, 0x77, 0x75, 0xcb, 0x08, 0x26, 0x40, 0xdf, 0x6d, 0x61, 0x58, 0x84, 0x0b, 0x48, 0xb6, 0xc6,
	0xeb, 0x93, 0xf6, 0x9a, 0xc5, 0x78, 0x0b, 0xb3, 0x5d, 0x5b, 0x16, 0xb6, 0xca, 0x19, 0x0d, 0xce,
	0xc7, 0xdb, 0x76, 0xbf, 0xcb, 0x74, 0x7d, 0x62, 0x93, 0x80, 0x7b, 0x97, 0x9b, 0x2a, 0xc4, 0xd9,
	0x74, 0xf5, 0xfc, 0x27, 0x86, 0x07, 0x6d, 0x6d, 0x69, 0xae, 0x5f, 0x4a, 0xe4, 0x5c, 0x8d, 0xfc,
	0x1b, 0x00, 0x00, 0xff, 0xff, 0x83, 0x8b, 0x87, 0xfe, 0x8d, 0x01, 0x00, 0x00,
}
